'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace ASPxPivotGridLayoutUpgradeEvent
    
    Partial Public Class _Default
        
        '''<summary>
        '''ASPxButtonSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ASPxButtonSave As Global.DevExpress.Web.ASPxButton
        
        '''<summary>
        '''ASPxPivotGridOld control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ASPxPivotGridOld As Global.DevExpress.Web.ASPxPivotGrid.ASPxPivotGrid
        
        '''<summary>
        '''fieldProductName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fieldProductName As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
        
        '''<summary>
        '''fieldCategoryName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fieldCategoryName As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
        
        '''<summary>
        '''fieldExtendedPrice control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fieldExtendedPrice As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
        
        '''<summary>
        '''fieldYear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fieldYear As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
        
        '''<summary>
        '''fieldQuarter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fieldQuarter As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
        
        '''<summary>
        '''ASPxButtonRestore control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ASPxButtonRestore As Global.DevExpress.Web.ASPxButton
        
        '''<summary>
        '''ASPxPivotGridNew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ASPxPivotGridNew As Global.DevExpress.Web.ASPxPivotGrid.ASPxPivotGrid
        
        '''<summary>
        '''fieldCountry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fieldCountry As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
        
        '''<summary>
        '''fieldSalesPerson control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fieldSalesPerson As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
        
        '''<summary>
        '''fieldProductName2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fieldProductName2 As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
        
        '''<summary>
        '''fieldCategoryName2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fieldCategoryName2 As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
        
        '''<summary>
        '''fieldExtendedPrice2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fieldExtendedPrice2 As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
        
        '''<summary>
        '''SqlDataSource2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SqlDataSource2 As Global.System.Web.UI.WebControls.SqlDataSource
    End Class
End Namespace
